version: '3'

services:
  minecraft-server:
    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"
      MOTD: "DB does Minecraft hype hype hype"
      # IMG: '/data/db.png'
      MEMORY: '1536M'

    image: itzg/minecraft-server

    volumes:
    - ./minecraft-data:/data

    container_name: minecraft

    tty: true
    stdin_open: true
    restart: always
